[package]
name = "kvs"
version = "0.1.0"
edition = "2018"
authors = ["ztelur <ztelur@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"